plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.12'
}

dependencies {
    implementation 'org.json:json:20240303'
    implementation 'dev.harrel:json-schema:1.5.0'
    implementation 'com.sanctionco.jmail:jmail:1.6.3' // Needed for e-mail format validation

    // Ensure the platform launcher is available at test runtime
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.0'
}

version = '2.7.2-channel.1'

nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'nextflow-io'
    className = 'nextflow.validation.ValidationPlugin'
    extensionPoints = [
        'nextflow.validation.config.ValidationConfig',
        'nextflow.validation.ValidationExtension',
        'nextflow.validation.ValidationObserverFactory'
    ]

    test {
        useJUnitPlatform()
        jvmArgs += [
            '--add-opens', 'java.base/sun.net.www.protocol.ftp=ALL-UNNAMED'
        ]
    }
}
